project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "../"
preserve_hierarchy: true
files: [
  {
    source: "/src/main/resources/assets/viafabricplus/lang/en_us.json",
    translation: "/src/main/resources/assets/viafabricplus/lang/%locale_with_underscore%.json",
    escape_quotes: 0,
    escape_special_characters: 0
  }
]
