# Gradle Properties
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Project Details
jvm_version=25

project_group=com.viaversion
project_name=ViaFabricPlus
project_version=4.6.3
project_description=Minecraft Fabric mod that allows you to join EVERY Minecraft server version (Classic, Alpha, Beta, Release, April Fools, Bedrock)

publish_owner_id=florianreuth
publish_owner_name=Florian Reuth
publish_owner_mail=git@florianreuth.de

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.158.0+26.2

# Set to empty to use the Minecraft version above, otherwise use version ranges: >=1.21.7 <=1.21.8
supported_minecraft_versions=
