name: Bug Report
description: Report a bug in ViaFabricPlus
labels: [ S-needs-triage, T-bug ]

body:
  - type: markdown
    attributes:
      value: |
        **Before reporting a bug, please see if using latest build from https://github.com/ViaVersion/ViaFabricPlus/actions fixes your issue.**
        Whenever you see fit, you can upload images or videos to any of the text fields.

  - type: textarea
    attributes:
      label: General Information
      description: |
        Please provide a ViaVersion dump, if you experience a crash, also the crash report (latest.log file). You can get both by
        going to `ViaFabricPlus -> Report issues` and using the buttons there.
      placeholder: |
        ViaVersion dump url: **paste here**
        Crash report url: **upload to mclo.gs and paste here**
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: |
        Describe the unexpected behavior.
        If you want to attach screenshots, use the comment field at the bottom of the page.
      placeholder: |
        Example: "Joining server xy causes my game to crash."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        List the steps on how we can reproduce the issue. Make sure I can easily understand what you mean with each step.
      placeholder: |
        Example:
        1. Joining server xy with version 1.14.4
        2. Game crashes
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe what exactly you expected to happen.
      placeholder: |
        Example: "the game should not crash when I join server xy."
    validations:
      required: true