name: crowdin-sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          config: .github/crowdin.yml
          upload_sources: true
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_base_branch_name: main
          pull_request_title: "New Crowdin Translations"
          pull_request_body: "New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)"
          commit_message: "[ci skip] Updated translations from Crowdin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
